version: '3.8'
services:
  registration_back:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_registration_back:latest
    container_name: users_registration_back
    restart: "no"
    tty: false 
    ports:
      - 5676:5676
      - 8080:8080
    environment:
      - APP_MODE=$APP_MODE
      - LOG_LEVEL=$LOG_LEVEL
      - IP=$IP
      - PORT=$PORT
      - PIRPOS_USER_NAME=$PIRPOS_USER_NAME
      - PIRPOS_PASSWORD=$PIRPOS_PASSWORD

  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: swagger-ui
      ports:
        - "8070:8080"
      volumes:
        - ./docs:/api
      environment:
        SWAGGER_JSON: /api/openapi.yaml
